version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4000M
        reservations:
          cpus: '2.0'
          memory: 4000M
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4000M
        reservations:
          cpus: '2.0'
          memory: 4000M
    depends_on:
        - zookeeper
    ports:
        - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9700:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"

networks:
  default:
    external: true
    name: mq-tests-network