version: '3.9'

services:
  #Service for nameserver
  mqtest-artemis:
    image: vromero/activemq-artemis
    container_name: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: mq-test
      ARTEMIS_PASSWORD: mq-test
      ARTEMIS_MIN_MEMORY: "2000M"
      ARTEMIS_MAX_MEMORY: "4000M"
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4000M
        reservations:
          cpus: '2.0'
          memory: 4000M

networks:
  default:
    external: true
    name: mq-tests-network