version: '3.9'

services:

  standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4000M
        reservations:
          cpus: '2.0'
          memory: 4000M

  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://standalone:8080
    cpuset: "6,7"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4000M
        reservations:
          cpus: '2.0'
          memory: 4000M

networks:
  default:
    external: true
    name: mq-tests-network